### ISSUE TITLE
Test post-conditions

### ISSUE THREAD

**Issue by chanwit** [swasd/dpm#4]
After each provision step, we must run a set of test cases came with the package to verify that the system is provisioned properly.

Here's a proposed syntax

```

---
  - test:
      when: docker ps --filter name=consul --format "{{.Names}}"
      exit: 0
      expect: consul
```

The above example is a test to confirm that container named `consul` is running properly after its provision and composition steps.
